spring:
  application:
    name: Workflow_Test_Integration
  kafka:
    bootstrap-servers: localhost:29092
ioevent:
  prefix: Samples
  group_id: Samples
  api_key: 23cc2452-b86b-4265-b52d-ec85a48a1172
server:
  port: 8083